// Code generated by gcg. DO NOT EDIT.

package example_test

func NewHoge(a int, b Fuga, c Foo) *Hoge {
	st := MakeHoge(a, b, c)
	return &st
}

func MakeHoge(a int, b Fuga, c Foo) Hoge {
	return Hoge{
		A: a,
		B: b,
		C: c,
	}
}

func NewFuga(c *int, d []string, e *[]*[]*[]*[]string, g interface{}) *Fuga {
	st := MakeFuga(c, d, e, g)
	return &st
}

func MakeFuga(c *int, d []string, e *[]*[]*[]*[]string, g interface{}) Fuga {
	return Fuga{
		C: c,
		D: d,
		E: e,
		G: g,
	}
}
