// Code generated by gcg. DO NOT EDIT.

package example_test

func NewHoge(a int, b Fuga, c Foo) *Hoge {
	return &Hoge{
		A: a,
		B: b,
		C: c,
	}
}

func NewFuga(a *int, b []string, c *[]*[]*[]*[]string, d interface{}, e map[*Hoge]map[*Fuga]*Hoge) *Fuga {
	return &Fuga{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
	}
}
