// Code generated by gcg. DO NOT EDIT.

package model

func NewFile(package_ string, imports []Import, structs []Struct) *File {
	return &File{
		Package: package_,
		Imports: imports,
		Structs: structs,
	}
}

func NewImport(name string, path string) *Import {
	return &Import{
		Name: name,
		Path: path,
	}
}

func NewStruct(name string, fields []Field, isPrivate bool) *Struct {
	return &Struct{
		Name:      name,
		Fields:    fields,
		IsPrivate: isPrivate,
	}
}

func NewField(name Name, type_ Type) *Field {
	return &Field{
		Name: name,
		Type: type_,
	}
}

func NewName(original string, argument string) *Name {
	return &Name{
		Original: original,
		Argument: argument,
	}
}

func NewType(isStar bool, prefix Prefix, package_ string, name string) *Type {
	return &Type{
		IsStar:  isStar,
		Prefix:  prefix,
		Package: package_,
		Name:    name,
	}
}
