// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/ras0q/gcg/internal/handler"
	"github.com/ras0q/gcg/internal/service"
)

// Injectors from wire.go:

func NewHandlers() *handler.Handlers {
	generatorService := service.NewGeneratorService()
	analyzerService := service.NewAnalyzerService()
	services := service.NewServices(generatorService, analyzerService)
	handlers := handler.NewHandlers(services)
	return handlers
}
