// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/Ras96/gcg/internal/handler"
	"github.com/Ras96/gcg/internal/repository"
)

// Injectors from wire.go:

func NewHandlers() *handler.Handlers {
	generatorRepository := repository.NewGeneratorRepository()
	analyzerRepository := repository.NewAnalyzerRepository()
	repositories := repository.NewRepositories(generatorRepository, analyzerRepository)
	handlers := handler.NewHandlers(repositories)
	return handlers
}
